services:
  - type: web
    name: smart-ehs-system
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "
      import os
      import sqlite3
      from pathlib import Path
      
      # Create directories
      for directory in ['static/uploads', 'static/exports', 'static/labels', 'data']:
          Path(directory).mkdir(parents=True, exist_ok=True)
          
      # Initialize database
      conn = sqlite3.connect('data/smart_ehs.db')
      conn.close()
      print('✅ Smart EHS System initialized successfully!')
      "
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///data/smart_ehs.db
      - key: USE_GPU
        value: false
