services:
  - type: web
    name: smart-ehs-system
    env: python
    runtime: python-3.11.9
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install Flask==3.0.0 gunicorn==21.2.0 python-dotenv==1.0.0
      python -c "
      import os
      import sqlite3
      from pathlib import Path
      
      # Create directories
      for directory in ['static/uploads', 'static/exports', 'static/labels', 'data']:
          Path(directory).mkdir(parents=True, exist_ok=True)
          print(f'Created directory: {directory}')
          
      # Initialize database
      conn = sqlite3.connect('data/smart_ehs.db')
      conn.close()
      print('✅ Smart EHS System initialized successfully!')
      "
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///data/smart_ehs.db
